twig:
    file_name_pattern: '*.twig'

when@test:
    twig:
      #    strict_variables: true

    paths:
        # pointe vers votre dossier d'images
        '%kernel.project_dir%/assets/images': images
          # point this wherever your css files live
        '%kernel.project_dir%/assets/styles': styles